services:
    glory_order.order_manager:
        class: Glory\DoctrineManager\DoctrineManager
        arguments: ['@doctrine']
    glory_order.item_listener:
        class: Glory\Bundle\OrderBundle\EventListener\ItemListener
        tags:
            -  { name: doctrine.event_subscriber }
